apiVersion: apps/v1
kind: Deployment
metadata:
  name: disk-access
  namespace: ${KUBE_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disk-access
  template:
    metadata:
      labels:
        app: disk-access
    spec:
      containers:
      - name: disk-access
        image: ghcr.io/andromeda-ai/utility-box-docker:fc5c71f00fe9306841207ff9a95f97678197f8bc
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: shared-disk
          mountPath: /mnt/shared-disk
        - name: workspace
          mountPath: /app/workspace
      volumes:
      - name: shared-disk
        persistentVolumeClaim:
          claimName: shared-disk
      - name: workspace
        emptyDir: {}