apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quick-app
  namespace: tenant-ac-machine
spec:
  replicas: 1
  serviceName: quick-app
  selector:
    matchLabels:
      app: quick-app
  template:
    metadata:
      labels:
        app: quick-app
    spec:
      restartPolicy: Always

      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 86400
      - key: "node.kubernetes.io/network-unavailable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 86400

      terminationGracePeriodSeconds: 300
      containers:
      - name: quick-app
        image: crtag/quick-app-managed:1.1.8
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - |
                # Pass if no MPI process (waiting for jobs)
                if ! pgrep -x quick.cuda.MPI > /dev/null; then
                  exit 0
                fi
                # If process exists, check if it's zombie
                if pgrep -x quick.cuda.MPI | xargs -I {} ps -o state= -p {} | grep -q '^Z'; then
                  # Found zombie process, fail the probe
                  exit 1
                fi
                # Process exists and is not zombie - pass
                exit 0
          initialDelaySeconds: 180
          periodSeconds: 120
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              # Container is ready if either:
              # 1. No MPI process (waiting for jobs)
              # 2. MPI process exists and is not zombie
              ! pgrep -x quick.cuda.MPI > /dev/null || \
              ! pgrep -x quick.cuda.MPI | xargs -I {} ps -o state= -p {} | grep -q '^Z'
          initialDelaySeconds: 180
          periodSeconds: 120
          timeoutSeconds: 10
          failureThreshold: 3
        env:
        - name: GOOGLE_CLOUD_SA_KEY # Google Cloud Service Account Key JSON
          valueFrom:
            secretKeyRef:
              name: gcloud-sa-key
              key: service-account.json
        - name: API_URL_JOB_ASSIGNMENT
          valueFrom:
            configMapKeyRef:
              name: quick-app-config
              key: api.job.url
        - name: API_URL_STATUS_REPORT
          valueFrom:
            configMapKeyRef:
              name: quick-app-config
              key: api.status.url
        - name: STATUS_CHECK_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: quick-app-config
              key: status.check.interval
        volumeMounts:
        - name: andromeda-shared-disk
          mountPath: /mnt/shared-disk
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: andromeda-shared-disk
        persistentVolumeClaim:
          claimName: andromeda-shared-disk