apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quick-app
  namespace: tenant-ac-machine
spec:
  replicas: 1
  serviceName: quick-app
  selector:
    matchLabels:
      app: quick-app
  template:
    metadata:
      labels:
        app: quick-app
    spec:
      restartPolicy: Always
      containers:
      - name: quick-app
        image: crtag/quick-app-managed:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - |
                if pgrep -x quick.cuda.MPI >/dev/null; then
                  pgrep -x quick.cuda.MPI | xargs -I {} ps -o state= -p {} | grep -qv '^Z'
                else
                  exit 1
                fi
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 4
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - >
              ! pgrep -x quick.cuda.MPI || 
              (pgrep -x quick.cuda.MPI | xargs -I {} ps -o state= -p {} | grep -vq '^Z')
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: GOOGLE_CLOUD_SA_KEY # Google Cloud Service Account Key JSON
          valueFrom:
            secretKeyRef:
              name: gcloud-sa-key
              key: service-account.json
        - name: API_URL_JOB_ASSIGNMENT
          valueFrom:
            configMapKeyRef:
              name: quick-app-config
              key: api.job.url
        - name: API_URL_STATUS_REPORT
          valueFrom:
            configMapKeyRef:
              name: quick-app-config
              key: api.status.url
        - name: STATUS_CHECK_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: quick-app-config
              key: status.check.interval
        volumeMounts:
        - name: andromeda-shared-disk
          mountPath: /mnt/shared-disk
        resources:
          limits:
            nvidia.com/gpu: 1 
      volumes:
      - name: andromeda-shared-disk
        persistentVolumeClaim:
          claimName: andromeda-shared-disk