apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: disk-access
  namespace: tenant-ac-machine
spec:
  replicas: 1
  serviceName: disk-access
  selector:
    matchLabels:
      app: disk-access
  template:
    metadata:
      labels:
        app: disk-access
    spec:
      containers:
      - name: disk-access
        image: ghcr.io/andromeda-ai/utility-box-docker:fc5c71f00fe9306841207ff9a95f97678197f8bc
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: andromeda-shared-disk
          mountPath: /mnt/shared-disk
      volumes:
      - name: andromeda-shared-disk
        persistentVolumeClaim:
          claimName: andromeda-shared-disk