apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: andromeda-shared-disk
  namespace: tenant-ac-machine
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi