apiVersion: v1
kind: Pod
metadata:
  name: quick-app
spec:
  restartPolicy: OnFailure
  containers:
    - name: quick-app
      image: "crtag/quick-app:1.0.0"
      command: ["tail", "-f", "/dev/null"]
      resources:
        limits:
          nvidia.com/gpu: 1