apiVersion: v1
kind: Pod
metadata:
  name: terachem-runtime-test
  namespace: tenant-ac-machine
spec:
  restartPolicy: OnFailure
  imagePullSecrets:
    - name: mps-registry-secret
  containers:
    - name: terachem-runtime-test
      image: "code.mps.inc/mps/terachem:runtime"
      command: ["tail", "-f", "/dev/null"]
      resources:
        limits:
          nvidia.com/gpu: 1
      volumeMounts:
        - name: shared-folder
          mountPath: /mnt/shared-folder
  volumes:
    - name: shared-folder
      hostPath:
        path: /srv/k8s-shared/terachem
        type: DirectoryOrCreate