name: Publish QUICK Docker Images

on:
  push:
    branches: # Trigger the workflow on pushes to main or development branches
      - main 
      - development
    paths:
      - "QUICK/**" # Only trigger if there are changes in the docker folder
    tags:
      - "docker*" # Optionally, trigger for specific tags.
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME1: crtag/quick-app 
      DOCKER_IMAGE_VERSION1: 1.0.1

      DOCKER_IMAGE_NAME2: crtag/quick-app-managed
      DOCKER_IMAGE_VERSION2: 1.0.0 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Image 1
        run: |
          docker build -t $DOCKER_IMAGE_NAME1:${{ env.DOCKER_IMAGE_VERSION1 }} -t $DOCKER_IMAGE_NAME1:latest -f QUICK/Dockerfile .
          docker push $DOCKER_IMAGE_NAME1:${{ env.DOCKER_IMAGE_VERSION1 }}
          docker push $DOCKER_IMAGE_NAME1:latest

      - name: Build and push Image 2
        run: |
          docker build -t $DOCKER_IMAGE_NAME2:${{ env.DOCKER_IMAGE_VERSION2 }} -t $DOCKER_IMAGE_NAME2:latest -f QUICK/Dockerfile.managed .
          docker push $DOCKER_IMAGE_NAME2:${{ env.DOCKER_IMAGE_VERSION2 }}
          docker push $DOCKER_IMAGE_NAME2:latest
